### PR TITLE
I don't think you really need sudo here.

### PR DESCRIPTION
**Pull request by mcepl**

### CODE REVIEW

**Comment by oskopek** [comment]
I'm actually not able to do this without sudo (Fedora 22) ...

**Comment by martinwoodward** [comment]
Yeah - I def couldn't write to /opt/ as a normal user on RHEL.  Should I be extracting to a different directory?

**Comment by mcepl** [comment]
> Yeah - I def couldn't write to /opt/ as a normal user on RHEL. Should I be extracting to a different directory?

OK, then you are right for the first mkdir, but you should add `chown user:user /opt/dotnet` (using whatever is the user name) or just don't do it in `/opt` but in `$HOME`.

**Comment by martinwoodward** [comment]
Where should we have it go if we where doing an RPM?  Would /opt/dotnet be the right place?  Or should we be extracting to /usr/lib/dotnet and then creating a symlink in /usr/bin?

(I'm guessing there is probably a man page I should be reading here for the conventions - just having trouble tracking it down)

**Comment by martinwoodward** [comment]
I answered my own question by looking at the Debian packaging configuration https://github.com/dotnet/cli/tree/rel/1.0.0/packaging/debian.

The way that we'll install this as an RPM is to stick into a standard lib folder and then create a bunch of symlinks in a standard bin folder. But a quicker way to manually install a build is just to extract into a folder, stick that into your path and then define a DOTNET_HOME.

Therefore I'll update the instructions to dump into the users $HOME removing the need for sudo.

Thanks!

**Comment by mcepl** [comment]
> Where should we have it go if we where doing an RPM?

I think for the RPM world your best bet would be https://fedoraproject.org/wiki/SIGs/Mono (let not that word scare you, I believe they will welcome you with open arms, I wonder whether there are any plans for incorporating .Net Core, or whichever you spell it ;), in Fedora, and if they are not, they should be) or some OpenSUSE equivalent (which may be even more interesting for your purposes, but I don't know anything about them).

**Pull request closed without merging**
